# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
TARGET = Client
DESTDIR = ../x64/Debug
CONFIG += debug
CONFIG += C++17
LIBS += -L"."
LIBS += -lstdc++fs
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(Client.pri)
